repos:
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.12
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]

default_language_version:
  python: python3.12

default_stages: [pre-commit, pre-push]
